export default {
    wrapper: 'mb-4',
    noLineItemsLabel: 'w-full',
    buttonGroup: 'flex w-full flex-col gap-1',
    buttonWrapper: 'w-full text-center',
    proceedToCheckoutButton: 'w-full',
    proceedToCartButton: '',
    subTotalRow: 'flex justify-between',
    subTotalLabel: 'font-bold',
    subTotalValue: '',
    shippingRow: 'mb-4',
    shippingLoader: 'absolute flex size-full items-center justify-center',
    shippingLabel: '',
    shippingButton: 'p-1!',
    shippingSpinnerClasses: 'mr-2 size-8!',
    shippingCost: 'flex items-center',
    taxInformation: 'mb-4 text-xs',
    promotionRow: 'mb-4',
    promotionInputWrapper: 'flex w-full max-w-sm',
    promotionInput: 'w-full',
    promotionButton: '',
    cartEmpty: 'p-4 text-center text-gray-500',
    shippingContainer: 'flex justify-between w-full',
    quantityField: 'w-full flex justify-between items-center',
    quantityLabel: 'flex font-bold',
    quantityFieldContent: 'w-1/3',
    propertyOption: 'font-bold',
    imageContainer: 'w-20 text-center',
    image: 'h-20 border object-contain p-1',
    fallbackImage: 'h-20 border object-contain p-1',
    iconContainer: 'flex size-20 items-center justify-center border text-center',
    icon: 'size-8',
    wishlistWrapper: 'flex',
    wishlistButtonGhost: 'pl-0 pr-2',
    wishlistButtonLink: 'pl-0 text-xs',
    wishlistIcon: 'size-5',
    productWrapper: 'order-1 mb-4 flex w-5/6 flex-col text-left',
    cartImageWrapper: 'mb-2 w-auto',
    labelWrapper: 'font-bold',
    optionsWrapper: 'my-2 text-xs',
    productNumberWrapper: 'mb-2 text-xs',
    deliveryPositionWrapper: 'text-xs',
    wishlistWrapperProduct: 'mt-2 text-xs',
    quantityWrapper: 'order-3 mb-4 flex w-full items-center justify-between',
    unitPriceWrapper: 'order-5 flex w-full justify-end text-xs',
    totalPriceWrapper: 'order-4 flex w-full justify-end',
    discountWrapper: 'order-1 mb-4 flex w-5/6 flex-col text-left',
    discountImageWrapper: 'mb-2 w-auto',
    discountLabel: 'font-bold',
    discountTotalPriceWrapper: 'order-4 flex w-full justify-end',
    cartItemWrapperSpacing: 'py-4',
    cartItemRemoveWrapper: 'order-2 flex w-1/6 justify-end',
    cartItemRemoveIcon: 'size-4',
    layoutLoaderWrapper: 'relative',
    layoutLoaderDim: 'pointer-events-none opacity-50',
    layoutLoaderSpinnerContent: 'flex flex-wrap border-b',
    headerCartTrigger: 'relative',
    headerCartIcon: 'size-6',
    headerCartAmount: 'text-gray-900 cursor-pointer pl-4',
    headerCartTitleRow: 'mt-2 flex w-full items-end justify-between',
    headerCartTitleCount: 'pr-4',
    headerCartEmpty: 'p-4 text-center text-gray-500',
};
