name: Deploy Review App
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_ORG: '1162305'

jobs:
  review-app:
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: review-app-${{ github.event.number }}
    environment:
      name: review
      url: ${{ steps.deploy.outputs.url }}
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Review App
        id: deploy
        uses: superfly/fly-pr-review-apps@1.3.0
